require('plugins')
require('config.mason')
require('config.lspconfig')
require('config.cmp')
require('config.telescope')
require('config.tresitter')
require('config.onedark')
require('config.lualine')
